export const fairytails = {
    pigs: {
      name: 'Tři prasátka',
      cards: [
        {image: 'prasatka1.png',
        reverse: false,},
        {image: 'prasatka2.png',
        reverse: false,},
        {image: 'prasatka3.png',
        reverse: false,},
        {image: 'prasatka4.png',
        reverse: false,},
        {image: 'prasatka5.png',
        reverse: false,},
        {image: 'prasatka6.png',
        reverse: false,},
        {image: 'prasatka1.png',
        reverse: false,},
        {image: 'prasatka2.png',
        reverse: false,},
        {image: 'prasatka3.png',
        reverse: false,},
        {image: 'prasatka4.png',
        reverse: false,},
        {image: 'prasatka5.png',
        reverse: false,},
        {image: 'prasatka6.png',
        reverse: false,},
      ] 
    },
    redCap: {
      name: 'Červená Karkulka',
      images: ['obrazek3', 'obrazek4'],
    },
  }