export const fairytails = {
    pigs: {
      name: 'Tři prasátka',
      cards: [
        {id:0,
        image: 'prasatka1.png',
        reverse: false,},
        {id:1,
        image: 'prasatka2.png',
        reverse: false,},
        {id:2,
        image: 'prasatka3.png',
        reverse: false,},
        {id:3,
        image: 'prasatka4.png',
        reverse: false,},
        {id:4,
        image: 'prasatka5.png',
        reverse: false,},
        {id:5,
        image: 'prasatka6.png',
        reverse: false,},
        {id:6,
        image: 'prasatka1.png',
        reverse: false,},
        {id:7,
        image: 'prasatka2.png',
        reverse: false,},
        {id:8,
        image: 'prasatka3.png',
        reverse: false,},
        {id:9,
        image: 'prasatka4.png',
        reverse: false,},
        {id:10,
        image: 'prasatka5.png',
        reverse: false,},
        {id:11,
        image: 'prasatka6.png',
        reverse: false,},
      ] 
    },
    redCap: {
      name: 'Červená Karkulka',
      images: ['obrazek3', 'obrazek4'],
    },
  }